### ISSUE TITLE
STG Uploader

### ISSUE THREAD

**Issue by ma1co** [ma1co/OpenMemories-AppList#1]
@Bostwickenator
I've added your STG Uploader app to the list. It is now installable [here](https://sony-pmca.appspot.com/apps).

Version 1 is currently hard-coded in apps.yaml. Please host a yaml file yourself which describes the newest version. Something like this should do:

``` yaml

---
version: "1.0"
url: http://stg-uploader.s3-website-us-east-1.amazonaws.com/releases/stg-uploader-1.0.apk
desc: First cut
```

This will allow you to publish new versions by yourself. Just make sure to add the newset version on top of the file (separate the different versions by 3 dashes).

I'll add the link to the yaml file to apps.yaml when you give me the url.

**Comment by Bostwickenator** [comment]
Thanks, Ma1co I'll do this tomorrow.

**Comment by Bostwickenator** [comment]
Clearly I meant 9 tomorrows. https://www.stg-uploader.xyz/releases/releases.yaml

**Comment by ma1co** [comment]
Oh, just include the _release_ section. The file should look something like this:

``` yaml
---
version: "1.0"
url: https://www.stg-uploader.xyz/releases/stg-uploader-1.0.apk
desc: First cut
```
